# Generated by Django 3.1.3 on 2020-11-24 08:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorname', models.CharField(max_length=128, verbose_name='배우이름')),
                ('career', models.TextField(default='', verbose_name='대표 작품')),
                ('photo1', imagekit.models.fields.ProcessedImageField(upload_to='actor_images/')),
            ],
            options={
                'verbose_name': '배우 리스트',
                'verbose_name_plural': '배우 리스트',
                'db_table': 'actors_list',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorname', models.CharField(max_length=128, verbose_name='감독이름')),
                ('career2', models.TextField(default='', verbose_name='대표 작품')),
                ('photo2', imagekit.models.fields.ProcessedImageField(upload_to='director_images/')),
            ],
            options={
                'verbose_name': '감독 리스트',
                'verbose_name_plural': '감독 리스트',
                'db_table': 'directors_list',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=128, verbose_name='영화이름')),
                ('career3', models.TextField(default='', verbose_name='대표 작품')),
                ('photo3', imagekit.models.fields.ProcessedImageField(upload_to='movie_images/')),
            ],
            options={
                'verbose_name': '영화 리스트',
                'verbose_name_plural': '영화 리스트',
                'db_table': 'movies_list',
            },
        ),
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_1', models.TextField(default='', verbose_name='감독이름')),
                ('act1_1', models.TextField(default='', verbose_name='배우이름1')),
                ('act2_1', models.TextField(default='', verbose_name='배우이름2')),
                ('act3_1', models.TextField(default='', verbose_name='배우이름3')),
                ('act4_1', models.TextField(default='', verbose_name='배우이름4')),
                ('genre_1', models.TextField(default='', verbose_name='장르')),
                ('rating_1', models.TextField(default='', verbose_name='연령')),
                ('dist_1', models.TextField(default='', verbose_name='배급사')),
            ],
            options={
                'verbose_name': '섹션1 선택 리스트(감독1,배우4,옵션3)',
                'verbose_name_plural': '섹션1 선택 리스트(감독1,배우4,옵션3)',
                'db_table': 'section0110',
            },
        ),
        migrations.CreateModel(
            name='Section1_ActorLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section1_DirectorLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_1', models.TextField(default='', verbose_name='영화 이름')),
            ],
            options={
                'verbose_name': '섹션1 감독 리스트',
                'verbose_name_plural': '섹션1 영화 리스트',
                'db_table': '_director_list',
            },
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.TextField(default='', verbose_name='영화 이름')),
                ('act1_2', models.TextField(default='', verbose_name='배우이름1')),
                ('act2_2', models.TextField(default='', verbose_name='배우이름2')),
                ('act3_2', models.TextField(default='', verbose_name='배우이름3')),
                ('act4_2', models.TextField(default='', verbose_name='배우이름4')),
            ],
            options={
                'verbose_name': '섹션2  선택 리스트(영화1,배우4)',
                'verbose_name_plural': '섹션2  선택 리스트(영화1,배우4)',
                'db_table': '_section02',
            },
        ),
        migrations.CreateModel(
            name='Section2_ActorLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act1_2', models.TextField(default='', verbose_name='배우이름1')),
                ('act2_2', models.TextField(default='', verbose_name='배우이름2')),
                ('act3_2', models.TextField(default='', verbose_name='배우이름3')),
                ('act4_2', models.TextField(default='', verbose_name='배우이름4')),
            ],
            options={
                'verbose_name': '섹션2 배우 리스트들',
                'verbose_name_plural': '섹션2 배우 리스트들',
                'db_table': '_actor_list',
            },
        ),
        migrations.CreateModel(
            name='Section2_MovieLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.TextField(default='', verbose_name='영화 이름')),
            ],
            options={
                'verbose_name': '섹션2 영화 리스트들',
                'verbose_name_plural': '섹션2 영화 리스트들',
                'db_table': '_movie_list',
            },
        ),
    ]
