# Generated by Django 3.1.3 on 2020-11-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section1_actorlists',
            options={'verbose_name': '섹션1 배우 리스트들', 'verbose_name_plural': '섹션1 배우 리스트들'},
        ),
        migrations.AlterModelOptions(
            name='section1_directorlists',
            options={'verbose_name': '섹션1 감독 리스트', 'verbose_name_plural': '섹션1 감독 리스트'},
        ),
        migrations.AddField(
            model_name='section1_actorlists',
            name='act1_1',
            field=models.TextField(default='', verbose_name='배우이름1'),
        ),
        migrations.AddField(
            model_name='section1_actorlists',
            name='act2_1',
            field=models.TextField(default='', verbose_name='배우이름2'),
        ),
        migrations.AddField(
            model_name='section1_actorlists',
            name='act3_1',
            field=models.TextField(default='', verbose_name='배우이름3'),
        ),
        migrations.AddField(
            model_name='section1_actorlists',
            name='act4_1',
            field=models.TextField(default='', verbose_name='배우이름4'),
        ),
        migrations.AlterModelTable(
            name='section1_actorlists',
            table='_actor_list1',
        ),
    ]
